spring:
  application:
    name: Meteor Madness
  config:
    import: optional:application-secrets.yml
  mvc:
    async:
      request-timeout: 120000
cors:
  allowed-origins: http://localhost:5173,http://127.0.0.1:5173,https://bugbustersfront.onrender.com